
import React, { useEffect, useRef, useState } from 'react';
import { Ayah, Surah, Language } from '../types';
import { IconClose, IconShare, IconSync, IconCopy } from './Icons';

interface AyahShareModalProps {
  ayah: Ayah;
  surah: Surah;
  language: Language;
  onClose: () => void;
}

const AyahShareModal: React.FC<AyahShareModalProps> = ({ ayah, surah, language, onClose }) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [sharing, setSharing] = useState(false);
  const [imgUrl, setImgUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    generateImage();
  }, [ayah, surah, language]);

  const drawPattern = (ctx: CanvasRenderingContext2D, width: number, height: number) => {
    ctx.save();
    ctx.strokeStyle = '#1999b315';
    ctx.lineWidth = 1;
    const step = 60;
    for (let x = 0; x <= width; x += step) {
      for (let y = 0; y <= height; y += step) {
        ctx.beginPath();
        ctx.arc(x, y, 2, 0, Math.PI * 2);
        ctx.stroke();
        // Рисуем легкие ромбы
        ctx.beginPath();
        ctx.moveTo(x, y - 20);
        ctx.lineTo(x + 20, y);
        ctx.lineTo(x, y + 20);
        ctx.lineTo(x - 20, y);
        ctx.closePath();
        ctx.stroke();
      }
    }
    ctx.restore();
  };

  const generateImage = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = 1080;
    canvas.height = 1350;

    // Background - Глубокий темный градиент
    const gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
    gradient.addColorStop(0, '#050505');
    gradient.addColorStop(0.5, '#0a0a0a');
    gradient.addColorStop(1, '#050708');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Рисуем узор
    drawPattern(ctx, canvas.width, canvas.height);

    // Рамка - Элегантная двойная линия
    ctx.strokeStyle = '#1999b366';
    ctx.lineWidth = 2;
    ctx.strokeRect(80, 80, canvas.width - 160, canvas.height - 160);
    ctx.strokeStyle = '#1999b322';
    ctx.lineWidth = 12;
    ctx.strokeRect(60, 60, canvas.width - 120, canvas.height - 120);

    // Декоративные уголки
    const cornerSize = 100;
    ctx.strokeStyle = '#1999b3';
    ctx.lineWidth = 4;
    // Top Left
    ctx.beginPath(); ctx.moveTo(60, 60 + cornerSize); ctx.lineTo(60, 60); ctx.lineTo(60 + cornerSize, 60); ctx.stroke();
    // Top Right
    ctx.beginPath(); ctx.moveTo(canvas.width - 60 - cornerSize, 60); ctx.lineTo(canvas.width - 60, 60); ctx.lineTo(canvas.width - 60, 60 + cornerSize); ctx.stroke();
    // Bottom Left
    ctx.beginPath(); ctx.moveTo(60, canvas.height - 60 - cornerSize); ctx.lineTo(60, canvas.height - 60); ctx.lineTo(60 + cornerSize, canvas.height - 60); ctx.stroke();
    // Bottom Right
    ctx.beginPath(); ctx.moveTo(canvas.width - 60 - cornerSize, canvas.height - 60); ctx.lineTo(canvas.width - 60, canvas.height - 60); ctx.lineTo(canvas.width - 60, canvas.height - 60 - cornerSize); ctx.stroke();

    // Header - Инфо о суре
    ctx.fillStyle = '#1999b3';
    ctx.font = 'bold 36px Lexend, sans-serif';
    ctx.textAlign = 'center';
    ctx.direction = 'ltr';
    const surahInfo = `${surah.englishName} • ${ayah.numberInSurah}`;
    ctx.fillText(surahInfo.toUpperCase(), canvas.width / 2, 180);

    // Arabic Text - Красивый шрифт Amiri
    ctx.fillStyle = '#ffffff';
    ctx.font = '72px Amiri, serif';
    ctx.direction = 'rtl';
    ctx.textAlign = 'center';
    // Находим центр для вертикального выравнивания
    wrapText(ctx, ayah.text, canvas.width / 2, 450, canvas.width - 240, 110);

    // Divider с декоративным элементом
    ctx.strokeStyle = '#1999b344';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(canvas.width / 2 - 200, 800);
    ctx.lineTo(canvas.width / 2 + 200, 800);
    ctx.stroke();
    
    // Маленький ромб в центре разделителя
    ctx.fillStyle = '#1999b3';
    ctx.save();
    ctx.translate(canvas.width/2, 800);
    ctx.rotate(Math.PI / 4);
    ctx.fillRect(-10, -10, 20, 20);
    ctx.restore();

    // Translation
    ctx.fillStyle = '#d4d4d8';
    ctx.font = '40px Lexend, sans-serif';
    ctx.direction = 'ltr';
    ctx.textAlign = 'center';
    const translation = ayah.translation || "";
    wrapText(ctx, translation, canvas.width / 2, 900, canvas.width - 280, 65);

    // Footer
    ctx.fillStyle = '#52525b';
    ctx.font = 'bold 24px Lexend, sans-serif';
    ctx.fillText('GENERATED BY NOBLE QURAN', canvas.width / 2, canvas.height - 120);

    setImgUrl(canvas.toDataURL('image/png', 1.0));
  };

  const wrapText = (ctx: CanvasRenderingContext2D, text: string, x: number, y: number, maxWidth: number, lineHeight: number) => {
    const words = text.split(' ');
    let line = '';
    let currentY = y;

    for (let n = 0; n < words.length; n++) {
      let testLine = line + words[n] + ' ';
      let metrics = ctx.measureText(testLine);
      let testWidth = metrics.width;
      if (testWidth > maxWidth && n > 0) {
        ctx.fillText(line, x, currentY);
        line = words[n] + ' ';
        currentY += lineHeight;
      } else {
        line = testLine;
      }
    }
    ctx.fillText(line, x, currentY);
  };

  const handleCopy = () => {
    const textToCopy = `${ayah.text}\n\n${ayah.translation}\n\n— Quran ${surah.number}:${ayah.numberInSurah}`;
    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    if (!imgUrl) return;
    setSharing(true);

    try {
      const response = await fetch(imgUrl);
      const blob = await response.blob();
      const file = new File([blob], `quran_ayah_${surah.number}_${ayah.numberInSurah}.png`, { type: 'image/png' });

      if (navigator.share && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title: `Ayah ${ayah.numberInSurah} of Surah ${surah.englishName}`,
          text: `“${ayah.translation}” — Quran ${surah.number}:${ayah.numberInSurah}`,
        });
      } else {
        const link = document.createElement('a');
        link.download = `quran_ayah_${surah.number}_${ayah.numberInSurah}.png`;
        link.href = imgUrl;
        link.click();
      }
    } catch (error) {
      console.error('Sharing failed:', error);
    } finally {
      setSharing(false);
    }
  };

  const t = {
    title: language === Language.RUSSIAN ? 'Поделиться аятом' : 'Share Ayah',
    shareBtn: language === Language.RUSSIAN ? 'Поделиться фото' : 'Share Image',
    copyBtn: language === Language.RUSSIAN ? 'Копировать текст' : 'Copy Text',
    copied: language === Language.RUSSIAN ? 'Скопировано!' : 'Copied!',
    close: language === Language.RUSSIAN ? 'Закрыть' : 'Close'
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/90 backdrop-blur-md animate-in fade-in duration-300">
      <div className="bg-[#121212] border border-white/10 rounded-[2.5rem] w-full max-w-sm overflow-hidden flex flex-col shadow-[0_32px_64px_-12px_rgba(0,0,0,0.8)] animate-in zoom-in-95 duration-300">
        <div className="p-5 border-b border-white/5 flex items-center justify-between">
          <h2 className="text-[10px] font-bold uppercase tracking-[0.3em] text-zinc-500">{t.title}</h2>
          <button onClick={onClose} className="w-8 h-8 flex items-center justify-center rounded-full bg-white/5 text-zinc-400 hover:text-white transition-colors">
            <IconClose />
          </button>
        </div>
        
        <div className="relative aspect-[4/5] bg-black/40 flex items-center justify-center p-3">
          {imgUrl ? (
            <img 
              src={imgUrl} 
              alt="Ayah Preview" 
              className="w-full h-full object-contain rounded-2xl shadow-2xl ring-1 ring-white/10" 
            />
          ) : (
            <div className="flex flex-col items-center gap-3">
               <div className="w-10 h-10 border-2 border-primary border-t-transparent rounded-full animate-spin"></div>
            </div>
          )}
          <canvas ref={canvasRef} className="hidden" />
        </div>

        <div className="p-6 grid grid-cols-1 gap-3">
          <button 
            disabled={sharing || !imgUrl}
            onClick={handleShare}
            className="w-full bg-primary text-white py-4 rounded-2xl font-bold flex items-center justify-center gap-3 active:scale-[0.97] transition-all disabled:opacity-50 shadow-lg shadow-primary/20"
          >
            {sharing ? <IconSync /> : <IconShare />}
            <span className="text-sm tracking-wide">{sharing ? '...' : t.shareBtn}</span>
          </button>
          
          <button 
            onClick={handleCopy}
            className={`w-full py-4 rounded-2xl font-bold flex items-center justify-center gap-3 active:scale-[0.97] transition-all border ${
              copied ? 'bg-green-500/10 border-green-500/20 text-green-500' : 'bg-white/5 border-white/5 text-zinc-300'
            }`}
          >
            {copied ? <div className="w-5 h-5 bg-green-500 rounded-full flex items-center justify-center text-white text-[10px]">✓</div> : <IconCopy />}
            <span className="text-sm tracking-wide">{copied ? t.copied : t.copyBtn}</span>
          </button>

          <button 
            onClick={onClose}
            className="w-full py-2 mt-2 text-zinc-600 font-bold text-[10px] uppercase tracking-[0.2em] hover:text-zinc-400 transition-colors"
          >
            {t.close}
          </button>
        </div>
      </div>
    </div>
  );
};

export default AyahShareModal;
